on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        pnpm-version: [10]
    steps:
      - name: release-please-action
        uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          release-type: node
          package-name: "@finpo/xhtml2pug"
      - name: Checkout
        uses: actions/checkout@v4.2.2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm install
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
